WeatherReport_Package/objects/LDC_Log_Object__c.object
<CustomObject>
    <description>This object is used to persist Error Logs</description>
    <label>LDC Log Object</label>
    <nameField>
        <displayFormat>Log-{0000}</displayFormat>
        <label>Log Object Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LDC Log Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>LDC_Function__c</fullName>
        <description>Displays the function from error</description>
        <label>Function</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

WeatherReport_Package/classes/LDC_LogObjectService_Test.cls
@isTest
private class LDC_LogObjectService_Test {

    @isTest
    static void insertLogObject_Test() {                
        Map<String, String> logError = new Map<String, String>();
        logError.put('function', 'LDCTEST');
        logError.put('message', 'This is a test');
        LDC_LogObjectService logger = new LDC_LogObjectService();
        logger.insertLogObject(logError);
        LDC_Log_Object__c logObject = [SELECT Id, LDC_Function__c FROM LDC_Log_Object__c WHERE LDC_Function__c = 'LDCTEST'];
        System.assertEquals(logObject.LDC_Function__c, 'LDCTEST');
    }
}