WeatherReport_Package/objects/LDC_Log_Object__c.object
<CustomObject>
    <description>This object is used to persist Error Logs</description>
    <label>LDC Log Object</label>
    <nameField>
        <displayFormat>Log-{0000}</displayFormat>
        <label>Log Object Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LDC Log Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>LDC_Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User woh is assigned the resolution of the error</description>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>LDC_Log_Objects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LDC_Category__c</fullName>
        <description>Category of the error</description>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Apex</fullName>
                </value>
                <value>
                    <fullName>Flow</fullName>
                </value>
                <value>
                    <fullName>Trigger</fullName>
                </value>
                <value>
                    <fullName>API</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LDC_Description__c</fullName>
        <description>Describes the error</description>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>LDC_Function__c</fullName>
        <description>Displays the function from error</description>
        <label>Function</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LDC_Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LDC_Status__c</fullName>
        <description>Define the status of the error</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

WeatherReport_Package/classes/LDC_LogObjectService.cls
/**
 * @author Laurent Dibo-Cohen
 * @version 1.0
 * @date 2024-02-09
 * @description : This class is used to manage the log objects persistence in Salesforce when an error occurs.
 */
public with sharing class LDC_LogObjectService {
    public void insertLogObject(Map<String, String> logData) {
        LDC_Log_Object__c logObject = new LDC_Log_Object__c();
        logObject = new LDC_Log_Object__c();
        logObject.LDC_Category__c = 'Apex';
        logObject.LDC_Priority__c = 'Medium';
        logObject.LDC_Assigned_To__c = UserInfo.getUserId();
        logObject.LDC_Status__c = 'Open';
        if (logData.get('function')!= null) {
            logObject.LDC_Function__c = logData.get('function');
        }
        if (logData.get('message')!= null) {
            logObject.LDC_Description__c = logData.get('message');
        }
        try {
            insert logObject;
        } catch (Exception e) {
            System.debug('LDC : Error inserting log object : ' + e.getMessage());
        }
    }
}