WeatherReport_Package/objects/LDC_Weather_Report__c.object
<CustomObject>
    <description>LDC - This object is created to persist weather reports for an Account or a User</description>
    <label>Weather Report</label>
    <nameField>
        <label>Weather Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Weather Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>LDC_Weather_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field links the weather report to an Account lookup relationship</description>
        <label>Weather Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Weather Reports</relationshipLabel>
        <relationshipName>LDC_Weather_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LDC_Weather_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field links the report to a User</description>
        <label>Weather User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>LDC_User_Weather_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/classes/LDC_WeaterReportService_Test.cls
@isTest
private class LDC_WeaterReportService_Test {
    @TestSetup
    static void setup(){
        Account account = new Account(
            Name = 'Test Account',
            BillingLatitude = 48.85341,
            BillingLongitude = 2.3488
        );
        insert account;
    }

    @isTest
    static void insertUserWeatherReport_Test() {
        LDC_WeaterReportService service = new LDC_WeaterReportService();
        String result;
        String PREFIX = 'WR';
        Id currentUserId = UserInfo.getUserId();
        LDC_WRP001_WeatherReport report = LDC_TestDataFactory.createTestWrapper();
        report.recordType = 'USER';
        report.recordId = currentUserId;

        result = LDC_WeaterReportService.insertWeatherReport(report);

        LDC_Weather_Report__c validateReport = [SELECT Id, LDC_Weather_User__c FROM LDC_Weather_Report__c WHERE LDC_Weather_User__c = :currentUserId LIMIT 1];
        System.assertEquals(validateReport.LDC_Weather_User__c, currentUserId);
    }
    @isTest
    static void insertAccountWeatherReport_Test() {
        LDC_WeaterReportService service = new LDC_WeaterReportService();
        String result;
        String PREFIX = 'WR';
        Account testAccount = [SELECT Id FROM Account WHERE Name='Test Account' LIMIT 1];
        LDC_WRP001_WeatherReport report = LDC_TestDataFactory.createTestWrapper();
        report.recordType = 'Account';
        report.recordId = testAccount.Id;

        result = LDC_WeaterReportService.insertWeatherReport(report); 
        LDC_Weather_Report__c validateReport = [SELECT Id, LDC_Weather_Account__c FROM LDC_Weather_Report__c WHERE LDC_Weather_Account__c = :testAccount.Id LIMIT 1];
        System.assertEquals(validateReport.LDC_Weather_Account__c, testAccount.Id);
    }
}